trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true

  - task: Checkout@1
    displayName: 'Checkout repository'

  - script: |
      python -m pip install --upgrade pip
      pip install selenium pytest pytest-trx
    displayName: 'Install dependencies'

  - script: |
      pytest automation/tests/ --trx=test-results/results.trx
    displayName: 'Run automated tests and generate .trx report'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/results.trx'
      failTaskOnFailedTests: true
      testRunTitle: 'QA Automation – Arxiv Papers (.trx)'
